services:
  - type: web
    name: crypto-saas
    env: docker
    repo: https://github.com/Gonzalo-Giraldo/crypto-saas
    branch: rebuild/minimal-core-py311
    rootDir: .
    dockerCommand: uvicorn apps.api.app.main:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: crypto-saas-binance-gateway-01
    env: docker
    repo: https://github.com/Gonzalo-Giraldo/crypto-saas
    branch: rebuild/minimal-core-py311
    rootDir: .
    dockerCommand: uvicorn apps.binance_gateway.main:app --host 0.0.0.0 --port $PORT
    plan: free
