STATE_PROVISIONAL_ACTIVE = "PROVISIONAL_ACTIVE"
STATE_AUTHORITATIVE_ACTIVE_EQUIVALENT = "AUTHORITATIVE_ACTIVE_EQUIVALENT"

REASON_OK = "REASON_OK"
REASON_INVALID_CURRENT_STATE = "REASON_INVALID_CURRENT_STATE"
REASON_RECONCILIATION_NOT_MATCHED = "REASON_RECONCILIATION_NOT_MATCHED"
REASON_CORRECTION_NOT_REQUIRED = "REASON_CORRECTION_NOT_REQUIRED"
REASON_PROTECTION_NOT_VERIFIABLE = "REASON_PROTECTION_NOT_VERIFIABLE"
REASON_EQUIVALENT_ACCEPTED = "REASON_EQUIVALENT_ACCEPTED"

REASON_CORRECTION_REQUIRED = "REASON_CORRECTION_REQUIRED"

STATE_AUTHORITATIVE_REPLACEMENT_PENDING = "AUTHORITATIVE_REPLACEMENT_PENDING"

STATE_PROVISIONAL_CLEANUP_PENDING = "PROVISIONAL_CLEANUP_PENDING"

STATE_AUTHORITATIVE_ACTIVE = "AUTHORITATIVE_ACTIVE"
STATE_STALE_PROVISIONAL_PRESENT = "STALE_PROVISIONAL_PRESENT"

STATE_TRAILING_READY = "TRAILING_READY"

REASON_AUTHORITATIVE_NOT_STABLE = "REASON_AUTHORITATIVE_NOT_STABLE"
