from apps.protection.constants import (
    STATE_PROVISIONAL_ACTIVE,
    STATE_AUTHORITATIVE_ACTIVE_EQUIVALENT,
    STATE_AUTHORITATIVE_REPLACEMENT_PENDING,
    STATE_PROVISIONAL_CLEANUP_PENDING,
    STATE_STALE_PROVISIONAL_PRESENT,
    STATE_AUTHORITATIVE_ACTIVE,
    STATE_TRAILING_READY,
)


ALLOWED_TRANSITIONS = {
    STATE_PROVISIONAL_ACTIVE: {
        STATE_AUTHORITATIVE_ACTIVE_EQUIVALENT,
        STATE_AUTHORITATIVE_REPLACEMENT_PENDING,
    },
    STATE_AUTHORITATIVE_REPLACEMENT_PENDING: {
        STATE_PROVISIONAL_CLEANUP_PENDING,
    },
    STATE_PROVISIONAL_CLEANUP_PENDING: {
        STATE_AUTHORITATIVE_ACTIVE,
        STATE_STALE_PROVISIONAL_PRESENT,
    },
    STATE_STALE_PROVISIONAL_PRESENT: {
        STATE_PROVISIONAL_CLEANUP_PENDING,
    },
    STATE_AUTHORITATIVE_ACTIVE: {
        STATE_TRAILING_READY,
    },
    STATE_AUTHORITATIVE_ACTIVE_EQUIVALENT: {
        STATE_TRAILING_READY,
    },
    STATE_TRAILING_READY: set(),
}
