"""create autopick observation snapshots

Revision ID: 6c42e5a61b4a
Revises: 
Create Date: 2026-05-17 12:18:22.525050
"""

from alembic import op
import sqlalchemy as sa



revision = '6c42e5a61b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autopick_observation_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('decision_status', sa.String(length=32), nullable=False),
    sa.Column('selected_symbol', sa.String(length=32), nullable=True),
    sa.Column('selected_rank', sa.Integer(), nullable=True),
    sa.Column('ranked_count', sa.Integer(), nullable=False),
    sa.Column('partial_failure_count', sa.Integer(), nullable=False),
    sa.Column('rejected_candidates_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index('ix_data_autopick_created_at', 'autopick_observation_snapshots', ['created_at'], unique=False)
    op.create_index('ix_data_autopick_decision_status', 'autopick_observation_snapshots', ['decision_status'], unique=False)
    op.create_index('ix_data_autopick_selected_symbol', 'autopick_observation_snapshots', ['selected_symbol'], unique=False)
    op.create_index('ix_data_autopick_snapshot_hash', 'autopick_observation_snapshots', ['snapshot_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_autopick_snapshot_hash', table_name='autopick_observation_snapshots')
    op.drop_index('ix_data_autopick_selected_symbol', table_name='autopick_observation_snapshots')
    op.drop_index('ix_data_autopick_decision_status', table_name='autopick_observation_snapshots')
    op.drop_index('ix_data_autopick_created_at', table_name='autopick_observation_snapshots')
    op.drop_table('autopick_observation_snapshots')
    # ### end Alembic commands ###
