from pydantic_settings import BaseSettings
from pydantic import ConfigDict


class Settings(BaseSettings):
    DATABASE_URL: str
    SECRET_KEY: str
    ENCRYPTION_KEY: str
    ENCRYPTION_KEY_VERSION: str = "v1"
    ENCRYPTION_KEY_PREVIOUS: str = ""
    ENCRYPTION_KEY_PREVIOUS_VERSION: str = ""
    BINANCE_SPOT_BASE_URL: str = ""
    BINANCE_TESTNET_BASE_URL: str = "https://testnet.binance.vision"
    BINANCE_FUTURES_BASE_URL: str = "https://testnet.binancefuture.com"
    BINANCE_GATEWAY_ENABLED: bool = False
    BINANCE_GATEWAY_BASE_URL: str = ""
    BINANCE_GATEWAY_TOKEN: str = ""
    BINANCE_GATEWAY_TIMEOUT_SECONDS: int = 12
    BINANCE_GATEWAY_FALLBACK_DIRECT: bool = True
    BINANCE_GATEWAY_STRICT_MODE: bool = False
    BINANCE_TICKER_CACHE_SECONDS: int = 20
    BINANCE_HTTP_MAX_RETRIES: int = 2
    BINANCE_HTTP_RETRY_BACKOFF_SECONDS: float = 0.6
    BINANCE_ORDER_RETRY_MAX_ATTEMPTS: int = 2
    BINANCE_ORDER_RETRY_BACKOFF_SECONDS: float = 0.7
    BINANCE_EXCHANGE_INFO_CACHE_SECONDS: int = 600
    BINANCE_PRICE_CACHE_SECONDS: int = 15
    BINANCE_MTF_CACHE_SECONDS: int = 60
    BINANCE_MTF_KLINES_LIMIT: int = 120
    AUTO_PICK_INTERNAL_SCHEDULER_ENABLED: bool = False
    AUTO_PICK_INTERNAL_SCHEDULER_INTERVAL_MINUTES: int = 5
    AUTO_PICK_INTERNAL_SCHEDULER_DRY_RUN: bool = True
    AUTO_PICK_INTERNAL_SCHEDULER_TOP_N: int = 10
    AUTO_PICK_INTERNAL_REAL_ONLY: bool = True
    AUTO_PICK_INTERNAL_INCLUDE_SERVICE_USERS: bool = False
    AUTO_PICK_INTERNAL_TENANT_ID: str = "default"
    AUTO_EXIT_INTERNAL_ENABLED: bool = False
    AUTO_EXIT_INTERNAL_DRY_RUN: bool = True
    AUTO_EXIT_INTERNAL_REAL_ONLY: bool = True
    AUTO_EXIT_INTERNAL_INCLUDE_SERVICE_USERS: bool = False
    AUTO_EXIT_INTERNAL_MAX_POSITIONS: int = 500
    AUTO_EXIT_INTERNAL_PAUSE: bool = False
    AUTO_EXIT_INTERNAL_MAX_CLOSES_PER_TICK: int = 2
    AUTO_EXIT_INTERNAL_SYMBOL_COOLDOWN_SECONDS: int = 300
    AUTO_EXIT_INTERNAL_MAX_ERRORS_PER_TICK: int = 3
    AUTO_PICK_REAL_GUARD_ENABLED: bool = False
    AUTO_PICK_REAL_ALLOWED_EMAILS: str = ""
    AUTO_PICK_REAL_ALLOWED_EXCHANGES: str = ""
    AUTO_PICK_REAL_ALLOWED_SYMBOLS: str = ""
    AUTO_PICK_REAL_BINANCE_QUOTE: str = "USDT"
    AUTO_PICK_REAL_REQUIRE_EXIT_PLAN: bool = True
    AUTO_PICK_REAL_EXIT_PLAN_MIN_RR: float = 1.2
    AUTO_PICK_REAL_EXIT_PLAN_MAX_HOLD_MINUTES: int = 240
    AUTO_PICK_REAL_EXIT_PLAN_MIN_RISK_PCT: float = 0.35
    AUTO_PICK_REAL_EXIT_PLAN_MAX_RISK_PCT: float = 3.0
    AUTO_PICK_REAL_EXIT_PLAN_ATR_MULTIPLIER: float = 0.8
    EXIT_TIME_MIN_PROGRESS_R: float = 0.5
    IBKR_BRIDGE_BASE_URL: str = ""
    RISK_PROFILE_MODEL2_EMAIL: str = ""
    RISK_PROFILE_LOOSE_EMAIL: str = ""
    DAILY_STOP: float
    MAX_TRADES: int
    AUTH_PUBLIC_REGISTER_ENABLED: bool = False
    AUTH_PASSWORD_MIN_LENGTH: int = 10
    AUTH_PASSWORD_REQUIRE_UPPER: bool = True
    AUTH_PASSWORD_REQUIRE_LOWER: bool = True
    AUTH_PASSWORD_REQUIRE_DIGIT: bool = True
    AUTH_PASSWORD_REQUIRE_SPECIAL: bool = True
    AUTH_LOGIN_RATE_LIMIT_ENABLED: bool = True
    AUTH_LOGIN_RATE_LIMIT_WINDOW_SECONDS: int = 300
    AUTH_LOGIN_RATE_LIMIT_MAX_ATTEMPTS: int = 7
    AUTH_2FA_LOGIN_ENABLED: bool = True
    AUTH_2FA_TEMP_DISABLE_UNTIL_UTC: str = ""
    AUTH_TOTP_VALID_WINDOW: int = 2
    ENFORCE_2FA_FOR_ADMINS: bool = False
    ENFORCE_2FA_EMAILS: str = ""
    ADMIN_RECOVERY_ENABLED: bool = False
    ADMIN_RECOVERY_TOKEN: str = ""
    SUPERUSER_EMAILS: str = "gonzalogiraldo@yahoo.com"
    PASSWORD_MAX_AGE_DAYS: int = 0
    ENFORCE_PASSWORD_MAX_AGE: bool = False
    TRADING_ENABLED_DEFAULT: bool = True
    RISK_INPUT_MAX_QTY: float = 1000000.0
    RISK_INPUT_MAX_PRICE: float = 10000000.0
    RISK_INPUT_MAX_OPENED_MINUTES: int = 10080
    MAX_OPEN_QTY_PER_SYMBOL: float = 0.0
    MAX_OPEN_NOTIONAL_PER_EXCHANGE: float = 0.0
    DEFAULT_CAPITAL_BASE_USD: float = 10000.0
    ALLOWED_BINANCE_SYMBOLS: str = ""
    ALLOWED_IBKR_SYMBOLS: str = ""
    IDEMPOTENCY_KEY_MAX_AGE_DAYS: int = 30
    AUDIT_EXPORT_SIGNING_KEY: str = ""
    LEARNING_PIPELINE_ENABLED: bool = True
    LEARNING_LABEL_HORIZON_MINUTES: int = 60
    LEARNING_LABEL_GRACE_MINUTES: int = 180
    LEARNING_LABEL_INTERVAL_MINUTES: int = 5
    LEARNING_RETENTION_ENABLED: bool = True
    LEARNING_RETENTION_INTERVAL_MINUTES: int = 60
    LEARNING_ROLLUP_INTERVAL_MINUTES: int = 60
    LEARNING_ROLLUP_MAX_ROWS: int = 50000
    LEARNING_RAW_TTL_DAYS: int = 180
    LEARNING_ROLLUP_TTL_DAYS: int = 730
    LEARNING_DECISION_RULES_WEIGHT: float = 0.9
    LEARNING_DECISION_MODEL_WEIGHT: float = 0.1
    LEARNING_DECISION_MIN_SAMPLES: int = 30
    LEARNING_DECISION_LOOKBACK_HOURS: int = 720
    LEARNING_DECISION_MAX_DELTA_POINTS: float = 6.0
    GITHUB_API_BASE_URL: str = "https://api.github.com"
    GITHUB_ACTIONS_OWNER: str = "Gonzalo-Giraldo"
    GITHUB_ACTIONS_REPO: str = "crypto-saas"
    GITHUB_ACTIONS_DEFAULT_BRANCH: str = "main"
    GITHUB_ACTIONS_READ_TOKEN: str = ""

    model_config = ConfigDict(
        env_file=".env",
        extra="ignore"
    )


settings = Settings()
